import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * LoginOrder.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class LoginOrder extends javax.swing.JFrame {

	/** Creates new form LoginOrder */
	public LoginOrder() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jOptionPane1 = new javax.swing.JOptionPane();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel2.setText("\u9884\u8ba2\u5ea7\u4f4d\u6570\uff1a");

		jLabel3.setText("\u9884\u8ba2\u5ea7\u4f4d\u7c7b\u578b\uff1a");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"经济舱", "商务舱" }));

		jButton2.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jButton2.setText("\u8fd4\u56de");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setFont(new java.awt.Font("微软雅黑", 0, 14));
		jButton3.setText("\u7f51\u4e0a\u652f\u4ed8");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton3ActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jButton1.setText("\u786e\u5b9a");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton1ActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(58, 58, 58)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton1)
																		.addGap(
																				41,
																				41,
																				41)
																		.addComponent(
																				jButton2)
																		.addGap(
																				32,
																				32,
																				32)
																		.addComponent(
																				jButton3))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel3))
																		.addGap(
																				59,
																				59,
																				59)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jComboBox1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								88,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(62, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(107, 107, 107)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(45, 45, 45)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												45, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton1)
														.addComponent(jButton3)
														.addComponent(jButton2))
										.addGap(30, 30, 30)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
			throws Exception {
		Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		Connection con = DriverManager.getConnection("jdbc:odbc:flight", "123",
				"123");
		Statement stmt = con.createStatement();
		String a = jTextField2.getText();
		String b = ((String) jComboBox1.getSelectedItem()).equals("经济舱") ? "经济舱"
				: "商务舱";
		
		if (a.equals("")) {
			jOptionPane1.showMessageDialog(null, "预订不成功！输入座位数为空。");
           return;
		}
		
		 ResultSet rs = stmt
				.executeQuery("select * from take_info WHERE OrderForm>=ALL(SELECT OrderForm FROM take_info);");
		if (rs.next()) {
			jOptionPane1.showMessageDialog(null, "添加订单成功！您的订单号为："
					+ rs.getLong("OrderForm") );

			stmt
					.executeUpdate("UPDATE take_info SET SeatNumber="
							+ a
							+ ",FlightType='"
							+ b
							+ "',IfPay='未付款' WHERE OrderForm>=ALL(SELECT OrderForm FROM take_info);");
			if (b.equals("经济舱")) {
				rs=stmt.executeQuery("select FlightNumber from take_info where OrderForm>=ALL(select OrderForm from take_info)");
				if(rs.next()){
					String c=rs.getString("FlightNumber");
				rs=stmt.executeQuery("select * from flight_info where FlightNumber='"+c+"'");
				if(rs.next()){
				String q=rs.getString("Cprice");
				
				
				stmt.executeUpdate("UPDATE take_info SET price="+a+"*"+q+" WHERE OrderForm>=ALL(SELECT OrderForm FROM take_info);");
						
				stmt.executeUpdate("UPDATE flight_info SET CheapNumber=CheapNumber-"
								+ a + " where FlightNumber='" + c + "'");
			}
				}
			}else {
				rs=stmt.executeQuery("select FlightNumber from take_info where OrderForm>=ALL(select OrderForm from take_info)");
				if(rs.next()){
					String d=rs.getString("FlightNumber");
				rs=stmt.executeQuery("select * from flight_info where FlightNumber='"+d+"'");
				if(rs.next()){
				String w=rs.getString("Bprice");
				stmt.executeUpdate("UPDATE take_info SET price="+w+"*"+a+" WHERE OrderForm>=ALL(SELECT OrderForm FROM take_info);");
				
				stmt.executeUpdate("UPDATE flight_info SET BusyNumber=BusyNumber-"
								+ a + " where FlightNumber='" + d + "'");

			
			}
			}
		}
		}
 else {
	jOptionPane1.showMessageDialog(null, "添加订单不成功！");

}

stmt.close();
con.close();
}
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)
			throws Exception {
		Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		Connection con = DriverManager.getConnection("jdbc:odbc:flight", "123",
				"123");
		Statement stmt = con.createStatement();
		ResultSet rs = stmt
				.executeQuery("select * from take_info where OrderForm>=ALL(SELECT OrderForm FROM take_info);");
		if (rs.next()) {
			if (rs.getString("FlightNumber") != null) {

				Payment s = new Payment();
				s.setVisible(true);
			} else {
				jOptionPane1.showMessageDialog(null, "没有添加订单！", "错误",
						jOptionPane1.ERROR_MESSAGE);
				return;
			}
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginOrder().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JOptionPane jOptionPane1;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables

}