import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * Upd_flight.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class Upd_flight extends javax.swing.JFrame {

	/** Creates new form Upd_flight */
	public Upd_flight() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

		jOptionPane1 = new javax.swing.JOptionPane();
		jOptionPane2 = new javax.swing.JOptionPane();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jLabel9 = new javax.swing.JLabel();
		jTextField7 = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		jTextField8 = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		jTextField9 = new javax.swing.JTextField();
		jLabel12 = new javax.swing.JLabel();
		jTextField10 = new javax.swing.JTextField();
		jLabel13 = new javax.swing.JLabel();
		jTextField11 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings
				.createAutoBinding(
						org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE,
						this, org.jdesktop.beansbinding.ELProperty
								.create("ÐÞ¸Äº½°à"), this,
						org.jdesktop.beansbinding.BeanProperty.create("title"));
		bindingGroup.addBinding(binding);

		jLabel1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel1.setText("\u822a\u73ed\u53f7\uff1a");

		jLabel2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel2.setText("\u8d77\u98de\u5730\uff1a");

		jLabel3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel3.setText("\u76ee\u7684\u5730\uff1a");

		jLabel4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel4.setText("\u8d77\u98de\u65f6\u95f4\uff1a");

		jTextField1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));

		jTextField2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));

		jTextField3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));

		jTextField4.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));

		jButton1.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 16));
		jButton1.setText("\u786e\u5b9a");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jButton1ActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jButton2.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 16));
		jButton2.setText("\u91cd\u7f6e");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 16));
		jButton3.setText("\u8fd4\u56de");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jLabel7.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 24));
		jLabel7.setText("\u4fee\u6539\u822a\u73ed");

		jLabel8.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel8.setText("\u5230\u8fbe\u65f6\u95f4\uff1a");

		jTextField6.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));

		jLabel9.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel9.setText("\u7ecf\u6d4e\u8231\u5ea7\u4f4d\u6570\uff1a");

		jTextField7.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		

		jLabel10.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel10.setText("\u7ecf\u6d4e\u8231\u4ef7\u683c\uff1a");

		jTextField8.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));

		jLabel11.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel11.setText("\u5546\u52a1\u8231\u5ea7\u4f4d\u6570\uff1a");

		jTextField9.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
	

		jLabel12.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel12.setText("\u5546\u52a1\u8231\u4ef7\u683c\uff1a");

		jTextField10.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));

		jLabel13.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));
		jLabel13.setText("\u8d77\u98de\u65e5\u671f\uff1a");

		jTextField11.setFont(new java.awt.Font("Î¢ÈíÑÅºÚ", 0, 18));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addGap(233, 233,
										233).addComponent(jLabel7)
										.addContainerGap(236, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(146, 146, 146)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1)
																		.addGap(
																				46,
																				46,
																				46)
																		.addComponent(
																				jButton2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				45,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton3))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jLabel9)
																						.addComponent(
																								jLabel10)
																						.addComponent(
																								jLabel11)
																						.addComponent(
																								jLabel12)
																						.addComponent(
																								jLabel13))
																		.addGap(
																				59,
																				59,
																				59)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jTextField11,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								101,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField10,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								101,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField9,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								101,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField8,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								101,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField6,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								101,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField7,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								101,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField4,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								101,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField3,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								101,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								101,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								101,
																								Short.MAX_VALUE))))
										.addGap(133, 133, 133)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(38, 38, 38)
										.addComponent(jLabel7)
										.addGap(30, 30, 30)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																29,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																29,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																29,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																29,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(
																jTextField6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jTextField7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel10)
														.addComponent(
																jTextField8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel11)
														.addComponent(
																jTextField9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel12)
														.addComponent(
																jTextField10,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel13)
														.addComponent(
																jTextField11,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(39, 39, 39)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton2)
														.addComponent(jButton3)
														.addComponent(jButton1))
										.addGap(69, 69, 69)));

		bindingGroup.bind();

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		jTextField1.setText("");
		jTextField2.setText("");
		jTextField3.setText("");
		jTextField4.setText("");
		jTextField6.setText("");
		jTextField7.setText("");
		jTextField8.setText("");
		jTextField9.setText("");
		jTextField10.setText("");
		jTextField11.setText("");

	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)
			throws Exception {
		Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
		Connection con = DriverManager.getConnection("jdbc:odbc:flight", "123",
				"123");
		Statement stmt = con.createStatement();
		String a = jTextField1.getText();
		String b = jTextField2.getText();
		String c = jTextField3.getText();
		String d = jTextField4.getText();
		String e = jTextField6.getText();
		String f = jTextField7.getText();
		String g = jTextField8.getText();
		String h = jTextField9.getText();
		String i = jTextField10.getText();
		String j = jTextField11.getText();

		if (a.equals("") || b.equals("") || c.equals("") || d.equals("")
				|| e.equals("") || f.equals("") || g.equals("") || h.equals("")
				|| i.equals("") || j.equals("")) {
			jOptionPane1.showMessageDialog(null, "ÄÚÈÝ²»ÄÜÎª¿Õ£¡", "´íÎó",
					jOptionPane1.ERROR_MESSAGE);
			return;
		}
		ResultSet rs = stmt
				.executeQuery("select * from take_info where FlightNumber='"
						+ a + "'");

		if(rs.next()) {
			if(a.equals(rs.getString("FlightNumber"))){
				jOptionPane1.showMessageDialog(null, "ÐÞ¸Ä²»³É¹¦£¡ÒÑ´æÔÚ¶©µ¥¡£");
			
		}}else {
			
			rs = stmt
			.executeQuery("select * from flight_info where FlightNumber='"
					+ a + "'");
			if(rs.next()){
			if(a.equals(rs.getString("FlightNumber"))){
			jOptionPane1.showMessageDialog(null, "ÐÞ¸Ä³É¹¦£¡");

			stmt.executeUpdate("UPDATE flight_info SET FlightNumber='" + a
					+ "',TakeoffPlace='" + b + "',destination='" + c
					+ "',TakeofftTime='" + d + "',ArriveTime='" + e
					+ "',CheapNumber=" + f + ",Cprice='" + g + "',BusyNumber="
					+ h + ",Bprice='" + i + "',FlightTime='" + j
					+ "' where FlightNumber='" + a + "'");
			}}else{
				jOptionPane1.showMessageDialog(null, "ÐÞ¸Ä²»³É¹¦£¡²»´æÔÚ¸Ãº½°à¡£");
			
			}
		}
		
		stmt.close();
		con.close();
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		dispose();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Upd_flight().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JOptionPane jOptionPane1;
	private javax.swing.JOptionPane jOptionPane2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField11;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	private org.jdesktop.beansbinding.BindingGroup bindingGroup;
	// End of variables declaration//GEN-END:variables

}